### ISSUE TITLE
A far fetched message...

### ISSUE THREAD

**Issue by acamilleri-seekers** [frenchfalcon/Hashtags#7]
Hi Scaraux, just trying to contact you about https://stackoverflow.com/questions/53714661/uicollectionviewcell-inconsistent-shadow-with-decoration-view

I have been stuck with this issue and was wondering what you `UICollectionViewFlowLayout` inheriting class was looking like

**Comment by acamilleri-seekers** [comment]
Especially before you are using IGList kit too but I have some issues that I think are related to it...

**Comment by scaraux** [comment]
Hey Mate @acamilleri-seekers, sorry for seeing that so late, you can chat with me on Twitter @scaraux :)
